version: '2.1'

services:
  book:
    platform: linux/amd64
    build: microservices/book-service
    mem_limit: 600m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy      

  comment:
    platform: linux/amd64
    build: microservices/comment-service
    mem_limit: 600m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy        

  rating:
    platform: linux/amd64
    build: microservices/rating-service
    mem_limit: 600m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy      

  book-theme-night:
    platform: linux/amd64
    build: microservices/book-theme-night-service
    mem_limit: 600m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
        
  book-composite:
    platform: linux/amd64
    build: microservices/book-composite-service
    mem_limit: 600m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      rabbitmq:
        condition: service_healthy
        
  eureka:
    platform: linux/amd64
    build: spring-cloud/eureka-server
    mem_limit: 600m
    ports:
      - "8761:8761"        
      
  mongodb:
    platform: linux/amd64
    image: mongo:4.4.14
    mem_limit: 350m
    ports:
      - "27017:27017"
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 10s
      timeout: 5s
      retries: 10
      
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    mem_limit: 350m
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=rating-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 5s
      retries: 10
      
  rabbitmq:
    platform: linux/amd64
    image: rabbitmq:3.7.8-management
    mem_limit: 350m
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10