logging:
  level:
    root: INFO
    microservices: DEBUG
    se.magnus: DEBUG

---
spring.profiles: docker

server.port: 8080

app:
  book-service:
    host: book
    port: 8080
  book-theme-night-service:
    host: book-theme-night
    port: 8080
  comment-service:
    host: comment
    port: 8080
  rating-service:
    host: rating
    port: 8080